# Generated by Django 4.1.7 on 2023-02-27 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apihandler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='img',
            field=models.CharField(max_length=500),
        ),
    ]
